#SCREEN
SCREEN_WIDTH = 1600
SCREEN_HEIGHT = 800

#AGV
AGV_SIZE = 30

#NAVIGATION
GRID_DENSITY = 5
GRID_OFFSET_AMOUNT = int(AGV_SIZE/GRID_DENSITY)

#ROOM
ROOM_WIDTH = 1000
ROOM_HEIGHT = 600
ROOM_W_OFFSET = (SCREEN_WIDTH - ROOM_WIDTH)/2
ROOM_H_OFFSET = (SCREEN_HEIGHT- ROOM_HEIGHT)/2

#COLORS
BLACK = (0,0,0)
WHITE = (255,255,255)

#PHYSICS
ROTATE_VAL = 100